config/routes.rb
Rails.application.routes.draw do
  resources :diaries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'diaries#index'
  get '/users', to: 'users#index'
  get '/users/new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  validates :title, presence: true, length: {maximum: 255}
  validates :body, presence: true, length: {maximum: 10_000}
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: [:show, :edit, :update, :destroy]

  def index
    @diaries = Diary.all
    @diaries = Diary.page(params[:page]).per(5)
  end

  def show
  end

  def new
    @diary = Diary.new
  end

  def edit
  end

  def create
    @diary = Diary.new(diary_params)

    respond_to do |format|
      if @diary.save
        format.html { redirect_to @diary, notice: '投稿しました。' }
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to @diary, notice: '編集しました。' }
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @diary.destroy
    respond_to do |format|
      format.html { redirect_to diaries_url, notice: '削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    def set_diary
      @diary = Diary.find(params[:id])
    end

    def diary_params
      params.require(:diary).permit(:title, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @hello = 'Hello, world!'
    render template: 'users/index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diaries/_form.html.haml
= form_with(model: diary, local: true) do |form|
  - if diary.errors.any?
    #error_explanation
      %h2
        = pluralize(diary.errors.count, "error")
        prohibited this diary from being saved:
      %ul
        - diary.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :タイトル
    = form.text_field :title, id: :diary_title
  .field
    = form.label :本文
    = form.text_area :body, id: :diary_body
  .actions
    = form.submit

app/views/diaries/edit.html.haml
%h1 編集
= render 'form', diary: @diary
= link_to '詳細', @diary
|
= link_to '戻る', diaries_path

app/views/diaries/index.html.haml
%p#notice= notice

.containerTwo
  
  %h1 投稿一覧
  
  %table
    %thead
      %tr
        %th タイトル
        %th 日付
    %tbody
      - @diaries.each do |diary|
        %tr
          %td= link_to diary.title, diary
          %td= diary.created_at
  %br/
  = link_to '投稿', new_diary_path
  = paginate @diaries

app/views/diaries/new.html.haml
%h1 新規投稿
= render 'form', diary: @diary
= link_to '戻る', diaries_path

app/views/diaries/show.html.haml
%p#notice= notice

%p
  %strong タイトル:
  = @diary.title
%p
  %strong 本文:
  = simple_format(@diary.body)
%p
  %strong 登録日時:
  = @diary.created_at
%p
  %strong 更新日時:
  = @diary.updated_at
= link_to '編集', edit_diary_path(@diary)
|
= link_to '削除', @diary, method: :delete, data: { confirm: '本当に削除しますか?' }
|
= link_to '一覧に戻る', diaries_path

app/views/layouts/application.html.haml
!!!
%html

  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Ochiaiapp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body

    %header
      = link_to 'T.Ochiai`s Diary', root_path
      
    %div.container
      = yield

    %footer ©T.ochiai

app/views/users/index.html.haml
.users-index= @hello

app/views/users/new.html.haml
%div test